config/routes.rb
Rails.application.routes.draw do
  resources :charity_targets do 
    get 'embed'
  end

  resources :hospitals, :controller => "charity_targets", :type => "Hospital"
  resources :schools, :controller => "charity_targets", :type => "School"
  resources :farmlands, :controller => "charity_targets", :type => "Farmland"

  mount Wupee::Engine, at: "/wupee"

  resources :badges
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'catalogue/index'
  get 'refresh_karma/(:paystairs_id)' => 'catalogue#refresh_karma', as: :refresh_karma

  get 'set_avatar' => 'catalogue#set_avatar', as: :choose_avatar
  get 'set_avatar/:id' => 'catalogue#set_avatar', as: :set_avatar

  root 'catalogue#index'

end

app/models/badge.rb
class Badge < ActiveRecord::Base
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :set_badge, only: [:show, :edit, :update, :destroy]

  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.all
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
  end

  # GET /badges/new
  def new
    @badge = Badge.new
  end

  # GET /badges/1/edit
  def edit
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(badge_params)

    respond_to do |format|
      if @badge.save
        format.html { redirect_to @badge, notice: 'Badge was successfully created.' }
        format.json { render :show, status: :created, location: @badge }
      else
        format.html { render :new }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /badges/1
  # PATCH/PUT /badges/1.json
  def update
    respond_to do |format|
      if @badge.update(badge_params)
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { render :show, status: :ok, location: @badge }
      else
        format.html { render :edit }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge.destroy
    respond_to do |format|
      format.html { redirect_to badges_url, notice: 'Badge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge
      @badge = Badge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def badge_params
      params.require(:badge).permit(:name, :description)
    end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/badges/_form.html.erb
<%= form_for(@badge) do |f| %>
  <% if @badge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@badge.errors.count, "error") %> prohibited this badge from being saved:</h2>

      <ul>
      <% @badge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/badges/edit.html.erb
<h1>Editing Badge</h1>

<%= render 'form' %>

<%= link_to 'Show', @badge %> |
<%= link_to 'Back', badges_path %>

app/views/badges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Badges</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @badges.each do |badge| %>
      <tr>
        <td><%= badge.name %></td>
        <td><%= badge.description %></td>
        <td><%= link_to 'Show', badge %></td>
        <td><%= link_to 'Edit', edit_badge_path(badge) %></td>
        <td><%= link_to 'Destroy', badge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Badge', new_badge_path %>

app/views/badges/new.html.erb
<h1>New Badge</h1>

<%= render 'form' %>

<%= link_to 'Back', badges_path %>

app/views/badges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @badge.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @badge.description %>
</p>

<%= link_to 'Edit', edit_badge_path(@badge) %> |
<%= link_to 'Back', badges_path %>