config/routes.rb
Rails.application.routes.draw do
  resources :charity_targets do 
    get 'embed'
  end

  resources :hospitals, :controller => "charity_targets", :type => "Hospital"
  resources :schools, :controller => "charity_targets", :type => "School"
  resources :farmlands, :controller => "charity_targets", :type => "Farmland"

  mount Wupee::Engine, at: "/wupee"

  resources :badges
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'catalogue/index'
  get 'refresh_karma/(:paystairs_id)' => 'catalogue#refresh_karma', as: :refresh_karma

  get 'set_avatar' => 'catalogue#set_avatar', as: :choose_avatar
  get 'set_avatar/:id' => 'catalogue#set_avatar', as: :set_avatar

  root 'catalogue#index'

end

app/controllers/catalogue_controller.rb
class CatalogueController < ApplicationController
  protect_from_forgery except: [:render_user, :refresh_karma]
  def index
  	@users = User.all
    @notifications = current_user.notifications if current_user
    @charity_targets = current_user.charity_targets if current_user
  end

  #include Merit::RankRulesMethods

  before_action :set_total_donated

  def set_total_donated
  	if current_user and params[:total_donated]
  		current_user.total_donated = params[:total_donated]
  	end
  end

  def refresh_karma
    paystairs_id = params[:paystairs_id]
    return unless paystairs_id

    user = User.find_by_paystairs_id(paystairs_id)
    if not user
      return unless current_user
      return if current_user.paystairs_id

      current_user.paystairs_id = paystairs_id
      current_user.save
      user = current_user
    end

    user.refresh_karma
    current_user.reload
    @notifications = current_user.notifications

    render "render_user.js.erb"
  end

  def set_avatar
  	redirect_to root_url and return if not current_user 

  	if params[:id]
  		avatar = params[:id]
  		current_user.avatar_type = avatar
  		current_user.save
  		flash[:notice] = "You successfully chose your avatar. Awesome!"
  		redirect_to root_url and return
  	end

  	render 'choose'
  end
end

app/helpers/catalogue_helper.rb
module CatalogueHelper
  	def avatar
  		if current_user.avatar_type
  			asset_path("avatars/" + current_user.avatar_type + ".png")
  		end
  	end

  	def country(user)
  		"from " + user.country if user and user.country
  	end
end

app/views/catalogue/choose.html.erb
  <div class="page-header">
    <h1>FAERIE</h1>
  </div>
  <p class="lead">Thank you for donating!</p>
  <p>Choose your avatar.</p>
  <div class="col-lg-2 col-md-2 col-xs-6 thumb">
    
        <%= link_to image_tag("faerie.png", class: "img-responsive"), set_avatar_path(id: 'faerie') %>
    
  </div>
  <div class="col-lg-2 col-md-2 col-xs-6 thumb">
    
        <%= link_to image_tag("goblin.png", class: "img-responsive"), set_avatar_path(id: 'goblin' ) %>
    
  </div>
  <div class="col-lg-2 col-md-2 col-xs-6 thumb">
    
        <%= link_to image_tag("warrior.png", class: "img-responsive"), set_avatar_path(id: 'warrior' ) %>
    
  </div>

    <div class="col-lg-2 col-md-2 col-xs-6 thumb">
    
        <%= link_to image_tag("wizard.png", class: "img-responsive"), set_avatar_path(id: 'wizard') %>
    
  </div>
  <div class="col-lg-2 col-md-2 col-xs-6 thumb">
    
        <%= link_to image_tag("dragon.png", class: "img-responsive"), set_avatar_path(id: 'dragon' ) %>
    
  </div>

app/views/catalogue/index.html.erb
<% content_for :hero do %>
  <div class="container-fluid">
    <div class="row">
      <div id="map" class="col-md-12" style='height: 500px;'></div>
    </div>
  </div>
<% end %>

  <div class="page-header">
    <h1>FAERIE</h1>
  </div>
  <p class="lead">Welcome to Faer.ie</p>
  <p>You have the following challenges available</p>

  <!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                 <h4 class="modal-title">Modal title</h4>

            </div>
            <div class="modal-body"><div class="te"></div></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->





  <div class="row">
  <% @users.each do |user| %>
  <% next unless user.avatar.present? %>
  <div class="col-lg-4 col-md-6 col-xs-6 thumb">
                <a class="thumbnail" href="#">
                    <%= image_tag(user.avatar.url(:original), class: "img-responsive") %>
                </a>
                <p><%= user.name %> <%= country(user) %></p>
                <script src='http://paystairs.com/button/button.js?recipientId=3'> </script>
  </div>
  <% end %>
  </div>

<script type="text/javascript">
  $(function() {

    <% if @charity_targets %>
      var map; // Global declaration of the map  
      iw = new google.maps.InfoWindow();

      function initialize()   
    {  
        var myOptions = {  
            zoom: 4,  
            center: new google.maps.LatLng(-6.208763, 106.845599 ),  
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            scrollwheel:  false
        }   
        map = new google.maps.Map(document.getElementById("map"), myOptions);  
         
        locations = [ 
        <% @charity_targets.each do |target| %>
        {
          "lat": <%= target.lat %>,
          "lng": <%= target.lng %>,
          "id": <%= target.id %>,
          "icon_url": "<%= image_url(target.background) %>",
          "infowindow": "Challenge id " + <%= target.id %> + ' <br/> <%= link_to "Open", url_for(target) %>'
        },
        <% end %>
        ];

        for (i = 0; i < locations.length; i++) {
          var icon = new google.maps.MarkerImage(
              locations[i]["icon_url"],
              null, /* size is determined at runtime */
              null, /* origin is 0,0 */
              null, /* anchor is bottom center of the scaled image */
              new google.maps.Size(64, 64)
          );  

          marker = new google.maps.Marker({
            position: new google.maps.LatLng(locations[i]["lat"], locations[i]["lng"]),
            map: map,
            icon: icon
          });

          google.maps.event.addListener(marker, 'click', (function(marker, i) {
            return function() {
              $.ajax({  
                url: '<%= charity_targets_url %>/' + locations[i]["id"] + '/embed',  
                success: function(data) {  
                        iw.setContent(data);  
                    iw.open(map, marker);  
                }  
            }); 
            }
          })(marker, i));
        }
    }  

    initialize();

    /*
      var handler = Gmaps.build('Google');

      handler.buildMap({ internal: {id: 'map'}}, function(){
        var markers = handler.addMarkers([
          <% @charity_targets.each do |target| %>
      {
        "lat": <%= target.latitude %>,
        "lng": <%= target.longitude %>,
        "infowindow": "Challenge id " + <%= target.id %> + ' <br/> <%= link_to "Open", url_for(target) %>'
      },
      <% end %>
        ]);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    <% end %>
    */


  	window.onmessage = function(ev) {
        var data = ev.data;

        if (data.type === 'paystairs-user') {
          /*notificationsChannel = pusher.subscribe('user-' + data.userId);
          notificationsChannel.bind('new_notification', function(notification){
              var message = notification.message;
              $('div.notification').text(message);
          });*/
        }

        if (data.type === 'paystairs-donation') {
        	<% if current_user and current_user.avatar_type %>
        		$.getScript("<%= url_for(refresh_karma_path)%>" + "/" + data.userId);
        		//window.location.href = "<%= root_url %>" + "?total_donated=" + data.total;
        	<% else %>
        		after_donated();
        	<% end %>
            /*alert('user ' + data.userId + ' donated $' + data.amount +
                ' to user ' + data.target + ', has donated ' +
                '$' + data.total + ' in total');*/
        }
    };

    $('#myModal').on('show.bs.modal', function (e) {
      iw.close();
      var link = $(e.relatedTarget);
      $(this).find(".modal-body").load(link.attr("data-href"));
      $(this).find('.modal-title').text(link.attr("data-title"))
      if(link.attr("data-fullwidth"))
        $(this).find(".modal-body").addClass("fullwidth");
      else
        $(this).find(".modal-body").removeClass("fullwidth");

      /*
      var button = $(event.relatedTarget) // Button that triggered the modal
      var recipient = button.data('whatever') // Extract info from data-* attributes
      // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
      // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
      var modal = $(this)
      modal.find('.modal-title').text('New message to ' + recipient)
      modal.find('.modal-body input').val(recipient)*/
    })

  	function after_donated() {
		window.location.href = "<%= url_for(choose_avatar_url) %>";
	}
})
</script>

app/views/catalogue/render_user.js.erb
$("#user").html("<%= escape_javascript(render partial: 'shared/user' ) %>");