config/routes.rb
Rails.application.routes.draw do
  resources :charity_targets do 
    get 'embed'
  end

  resources :hospitals, :controller => "charity_targets", :type => "Hospital"
  resources :schools, :controller => "charity_targets", :type => "School"
  resources :farmlands, :controller => "charity_targets", :type => "Farmland"

  mount Wupee::Engine, at: "/wupee"

  resources :badges
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'catalogue/index'
  get 'refresh_karma/(:paystairs_id)' => 'catalogue#refresh_karma', as: :refresh_karma

  get 'set_avatar' => 'catalogue#set_avatar', as: :choose_avatar
  get 'set_avatar/:id' => 'catalogue#set_avatar', as: :set_avatar

  root 'catalogue#index'

end

app/models/charity_target.rb
class CharityTarget < ActiveRecord::Base
	belongs_to :user

	def intro
		"Welcome to the farm!"
	end

	def background
		"none"
	end

	class << self

    def inherited(child)
      child.instance_eval do
        def model_name
          CharityTarget.model_name
        end
      end
      super 
    end
	end
end

app/controllers/charity_targets_controller.rb
class CharityTargetsController < ApplicationController
  before_action :set_charity_target, only: [:show, :edit, :update, :destroy]

  # GET /charity_targets
  # GET /charity_targets.json
  def index
    @charity_targets = CharityTarget.all
  end

  # GET /charity_targets/1
  # GET /charity_targets/1.json
  def show
    @game = @charity_target
    @notifications = current_user.notifications if current_user
  end

  def embed
    return unless params[:charity_target_id]
    @charity_target = CharityTarget.find(params[:charity_target_id])
    #@image = asset_url(@charity_target.type || "farmland" + ".png")
    @game = @charity_target
    render "embed", :layout => false 
  end

  # GET /charity_targets/new
  def new
    @charity_target = CharityTarget.new
  end

  # GET /charity_targets/1/edit
  def edit
  end

  # POST /charity_targets
  # POST /charity_targets.json
  def create
    @charity_target = CharityTarget.new(charity_target_params)

    respond_to do |format|
      if @charity_target.save
        format.html { redirect_to @charity_target, notice: 'Charity target was successfully created.' }
        format.json { render :show, status: :created, location: @charity_target }
      else
        format.html { render :new }
        format.json { render json: @charity_target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charity_targets/1
  # PATCH/PUT /charity_targets/1.json
  def update
    respond_to do |format|
      if @charity_target.update(charity_target_params)
        format.html { redirect_to @charity_target, notice: 'Charity target was successfully updated.' }
        format.json { render :show, status: :ok, location: @charity_target }
      else
        format.html { render :edit }
        format.json { render json: @charity_target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charity_targets/1
  # DELETE /charity_targets/1.json
  def destroy
    @charity_target.destroy
    respond_to do |format|
      format.html { redirect_to charity_targets_url, notice: 'Charity target was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charity_target
      @charity_target = CharityTarget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charity_target_params
      params.require(:charity_target).permit(:user_id, :type, :name, :latitude, :longitude)
    end
end

app/helpers/charity_targets_helper.rb
module CharityTargetsHelper
end

app/views/charity_targets/_form.html.erb
<%= form_for(@charity_target) do |f| %>
  <% if @charity_target.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charity_target.errors.count, "error") %> prohibited this charity_target from being saved:</h2>

      <ul>
      <% @charity_target.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charity_targets/_game.html.erb
<div class="container" style="padding: 0; height: 467px; position: relative;">
	<%= render "game/" + @charity_target.type.downcase %>
</div>

app/views/charity_targets/_intro.html.erb
<div class="container" style="width: 350px; height: 367px;">
	<div class="row">
		<div class="col-md-12">
			<%= image_tag @charity_target.background, class: "img-responsive", style: "height: 200px; margin: auto;" %>
		</div>
	</div>
	<div class="row text-center">
		<h3><%= @charity_target.name %></h3><p><%= @charity_target.description %></p>
<button type="button" class="btn btn-primary" data-toggle="modal" data-title="<%= @charity_target.name %>" data-href="<%= charity_target_embed_url(@charity_target, :game => true) %>" data-target="#myModal">Start</button>
	</div>
</div>

app/views/charity_targets/edit.html.erb
<h1>Editing Charity Target</h1>

<%= render 'form' %>

<%= link_to 'Show', @charity_target %> |
<%= link_to 'Back', charity_targets_path %>

app/views/charity_targets/embed.html.erb
<% if params[:game] %>
 <%= render "game" %>
<% else %>
 <%= render "intro" %>
<% end %>

app/views/charity_targets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Charity Targets</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Type</th>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @charity_targets.each do |charity_target| %>
      <tr>
        <td><%= charity_target.user_id %></td>
        <td><%= charity_target.type %></td>
        <td><%= charity_target.name %></td>
        <td><%= charity_target.latitude %></td>
        <td><%= charity_target.longitude %></td>
        <td><%= link_to 'Show', charity_target %></td>
        <td><%= link_to 'Edit', edit_charity_target_path(charity_target) %></td>
        <td><%= link_to 'Destroy', charity_target, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Charity target', new_charity_target_path %>

app/views/charity_targets/new.html.erb
<h1>New Charity Target</h1>

<%= render 'form' %>

<%= link_to 'Back', charity_targets_path %>

app/views/charity_targets/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container" style="padding: 0; height: 467px; position: relative;">
  <%= render "game/" + @charity_target.type.downcase %>
</div>
<!--
<p>
  <strong>User:</strong>
  <%= @charity_target.user_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @charity_target.type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @charity_target.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @charity_target.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @charity_target.longitude %>
</p>


<%= link_to 'Edit', edit_charity_target_path(@charity_target) %> |
<%= link_to 'Back', charity_targets_path %>

-->